### ISSUE TITLE
TypeError: 'tuple' object is not callable

### ISSUE THREAD

**Issue by guohai** [gumblex/htmllisting-parser#1]
Python 3.2.3 (default, Nov 17 2016, 01:04:00) 
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import htmllistparse
>>> cwd, listing = htmllistparse.fetch_listing("my url")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "htmllistparse.py", line 237, in fetch_listing
    req = requests.get(url, timeout=30)
  File "/usr/local/lib/python3.2/dist-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/usr/local/lib/python3.2/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.2/dist-packages/requests/sessions.py", line 422, in request
    prep = self.prepare_request(req)
  File "/usr/local/lib/python3.2/dist-packages/requests/sessions.py", line 360, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/local/lib/python3.2/dist-packages/requests/models.py", line 294, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.2/dist-packages/requests/models.py", line 328, in prepare_url
    url = str(url)
TypeError: 'tuple' object is not callable

Thanks if you can shed some light. Thanks in advance.

**Comment by gumblex** [comment]
The "my url" thing should be str.

**Comment by guohai** [comment]
Yes, when testing I use the real url 'http://192.168.99.149:8080/'

import htmllistparse
cwd, listing = htmllistparse.fetch_listing('http://192.168.99.149:8086/')

**Comment by gumblex** [comment]
What's the version of your `requests` library?

**Comment by guohai** [comment]
Name: requests
Version: 2.3.0

**Comment by gumblex** [comment]
Can't find the corresponding line in requests 2.3.0.
Your Python and requests library are too old. Even if `requests` works, other things may break. We suggest you use at least Python 3.3 and other up-to-date libraries.

**Comment by guohai** [comment]
Okay, thanks very much bro, I was using python3.2 and I'm now upgrade it to 3.3, works like a charm.
